# Generated by Django 5.2 on 2025-07-05 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
