# Generated by Django 5.2 on 2025-07-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitem',
            name='users',
        ),
    ]
