# Generated by Django 5.2 on 2025-07-03 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitem',
            name='users',
        ),
        migrations.CreateModel(
            name='CollectibleItemWithUsers',
            fields=[
                ('collectibleitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_run.collectibleitem')),
                ('users', models.ManyToManyField(related_name='items', related_query_name='query_items', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('app_run.collectibleitem',),
        ),
    ]
