# Generated by Django 5.2 on 2025-07-05 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
