# Generated by Django 5.2 on 2025-07-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_collectibleitem_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitem',
            name='users',
        ),
    ]
