# Generated by Django 5.2 on 2025-07-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_run.run'),
            preserve_default=False,
        ),
    ]
