# Generated by Django 5.2.4 on 2025-07-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_position_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='speed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
