# Generated by Django 5.2 on 2025-07-04 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_position_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('picture', models.URLField()),
                ('value', models.IntegerField()),
                ('users', models.ManyToManyField(blank=True, related_name='items', related_query_name='query_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
