# Generated by Django 5.2 on 2025-07-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_run_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.UUIDField()),
                ('latitude', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('picture', models.URLField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
