# Generated by Django 5.2 on 2025-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_collectibleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
