# Generated by Django 5.2 on 2025-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_position_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
