# Generated by Django 5.2 on 2025-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_position_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
