# Generated by Django 5.2 on 2025-07-03 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_collectibleitem_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='users',
            field=models.ManyToManyField(related_name='items', related_query_name='query_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
