# Generated by Django 5.2 on 2025-07-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_run_distance_collectibleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitem',
            name='users',
        ),
    ]
