# Generated by Django 5.2 on 2025-07-04 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_collectibleitem_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='items', related_query_name='query_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_run.run'),
        ),
    ]
