# Generated by Django 5.2 on 2025-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_alter_subscribe_athlete_alter_subscribe_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='score',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
